apache/logging-log4net

- src/log4net/AssemblyInfo.cs
- src/log4net/Core/LoggingEvent.cs
- src/log4net/Util/PropertiesDictionary.cs
- src/log4net/log4net.csproj
> Fix net40 client profile

- src/log4net/Appender/AdoNetAppender.cs
- src/log4net/Appender/FileAppender.cs
- src/log4net/Appender/SmtpAppender.cs
- src/log4net/Config/XmlConfigurator.cs
- src/log4net/Layout/Layout2RawLayoutAdapter.cs
- src/log4net/Layout/LayoutSkeleton.cs
- src/log4net/ObjectRenderer/RendererMap.cs
- src/log4net/Util/PatternString.cs
Fix CA2000, CA2237, CA3075
Also requires #66 otherwise nuget restore fails.
> Fix CA2000, CA2237, CA3075

- src/log4net/Appender/AdoNetAppender.cs
Using npgsql on netfx and mono I've encountered this error on an applicaiton startup:
```
log4net:ERROR [CustomAdoNetAppender] ErrorCode: GenericFailure. Exception while writing to database
Npgsql.PostgresException (0x80004005): 42601: syntax error at or near ":"
at Npgsql.NpgsqlConnector.DoReadMessage(Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isPrependedMessage)
at Npgsql.NpgsqlConnector.ReadMessage(Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications)
at Npgsql.NpgsqlConnector.ReadMessage(Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications)
at Npgsql.NpgsqlConnector.ReadExpecting[T](Boolean async)
at Npgsql.NpgsqlCommand.Prepare()
at …
```
> Fix AdoNetAppender using npgsql

- src/log4net/Appender/AdoNetAppender.cs
Same bug as #71.
npgsql@4.1.9 (above 4.* in general) completely destroys adonet appender.
3.* fails to prepare command but allows to execute it.
4+ fails to prepare and to execute.
> Fix AdoNetAppender using npgsql once again.

- src/log4net/Core/LoggingEvent.cs
After migrating to .NET 6 the %thread field became useless for threadpool threads. Restore logging of the numeric thread ID for this case.
> (LOG4NET-680) For %thread/%t, use the numeric thread ID for .NET worker pool threads

- install-dotnet-core-sdk-1.1.ps1
- install-net-framework-sdk-3.5.ps1
Enforce TLS 1.2 in PowerShell Scrips as Microsoft is deprecating all old TLS versions
> Enforcing TLS 1.2

- src/log4net/Appender/RemoteSyslogAppender.cs
We would like to write new lines in our log messages as '\n' literally.
To do this, I've extracted the existing logic into a new virtual method.
@fluffynuts Could you please review?
The main code churn is from normalizing the method to tabs instead of spaces.
> Extension point for handling new lines in RemoteSysLogAppender added

- .gitignore
- src/log4net/Util/SystemInfo.cs
We would like to make SystemInfo.EntryAssemblyLocation writable so that we can adjust its value for unit test projects.
.net core sets "testhost.dll" as EntryAssembly.
@fluffynuts Could you please review?
> SystemInfo.EntryAssemblyLocation writable to adjust location for config-files in unit test projects

- src/log4net/Appender/FileAppender.cs
We have a native application (Delphi) which loads .net dlls at runtime.
With this adjustment we can (optionally) share the log file between the native and the managed part of the application.
@fluffynuts Could you please review?
> New locking model for single log file in native applications with managed parts

- src/log4net/Appender/FileAppender.cs
- src/log4net/log4net.csproj
The creation of the locking model instance is now deferred to ActivateOptions() so that defaultLockingModelType has an effect.
+ Tabify all appender code files (were inconsistent)
+ include pdb file in nuget package fpr better debugging experience
@fluffynuts Could you please review?
> Defer creation of locking model to ActivateOptions()

- src/log4net/Util/LogicalThreadContextStack.cs
- src/log4net/Util/ThreadContextStack.cs
**Change**
Add `Peek()` method to `ThreadContextStack` and `LogicalThreadContextStack` to be able to get the most recent value from the context without removing it.
**Motivation**
In the scope of [ElasticCommonSchema .NET integration for log4net](https://github.com/elastic/ecs-dotnet/tree/main/src/Elastic.CommonSchema.Log4net) log entry properties are being read and written to ECS format. In case of context stacks [current implementation](https://github.com/elastic/ecs-dotnet/blob/main/src/Elastic.CommonSchema.Log4net/LoggingEventConverter.cs#L85) takes string representation of the stack. It works fine when stack (i.e., property) has a single value, but there are also cases when stack contains multiple values (same or different ones). With the proposed changes it will be able to take the …
> Add Peek() method to ThreadContextStack and LogicalThreadContextStack.

- examples/mono/1.0/Tutorials/ConsoleApp/cs/src/App.config
- examples/net/1.1/Tutorials/ConsoleApp/cpp/src/App.config
- examples/net/1.1/Tutorials/ConsoleApp/js/src/App.config
- examples/net/2.0/Appenders/SampleAppendersApp/cs/src/App.config
- examples/net/2.0/Tutorials/ConsoleApp/cs/src/App.config
- examples/net/2.0/Tutorials/ConsoleApp/vb/src/App.config
- src/log4net/Appender/AdoNetAppender.cs
CodeQL is falsly identifying the documentation examples of SQL Server connection strings violating [CodeQL: c# Password in configuration file Rule](https://codeql.github.com/codeql-query-help/csharp/cs-password-in-configuration/). Even though it's a false positive, many organizations take stances of not allowing dismissals and would rather see fixes for CodeQL findings. This proposed change will prevent this rule from being tripped in the future and not require organizations to mark these as false positives manually.
> Fix CodeQL Password in configuration file Rule False Positives

- src/log4net.Tests/Appender/RollingFileAppenderTest.cs
- src/log4net.Tests/log4net.Tests.csproj
- src/log4net/Appender/FileAppender.cs
For #118, intended for quick release in 2.0.17
> Fast fix for NullRefException from FileAppender

- src/site/xdoc/release/release-notes.xml
Hello
I noticed an issue on the Release Notes page which had the wrong version.
I have corrected this. Apologies if it's in the wrong place - I could find no other reference to it.
https://logging.apache.org/log4net/release/release-notes.html
Kind regards
Dan Atkinson
> Correct version number in release notes

- src/log4net.Tests/Util/LogLogTest.cs
- src/log4net/Util/LogLog.cs
fixes #134 IndexOutOfRangeException in LogLog.LogReceived
> Fix IndexOutOfRangeException in LogLog.LogReceived (#134)

- doc/MailTemplate.Announce.txt
- doc/MailTemplate.Result.txt
- doc/MailTemplate.txt
- package.json
- pom.xml
- scripts/update-version.ps1
- src/log4net.sln
- src/log4net/log4net.csproj
- src/site/xdoc/release/release-notes.xml
Update the log4net version in every relevant file via script
> automate version bumps

- scripts/build-preview.ps1
- src/log4net.Tests/Appender/FileAppenderTest.cs
- src/log4net/Util/TypeConverters/ConverterRegistry.cs
- src/site/xdoc/release/release-notes.xml
fixes a regression from changing to generic collections in 3.0.0
> a converter can implement IConvertTo AND IConvertFrom (fixes #183)

- scripts/build-preview.ps1
- src/log4net.Tests/Appender/Internal/SimpleTelnetClient.cs
- src/log4net.Tests/Appender/TelnetAppenderTest.cs
- src/log4net/Appender/TelnetAppender.cs
> #194 fixed a bug in the Dispose-Logic of TelnetAppender

- .editorconfig
- src/log4net.Tests/Hierarchy/HierarchyTest.cs
- src/log4net/Repository/Hierarchy/Hierarchy.cs
- src/log4net/Repository/Hierarchy/ProvisionNode.cs
- src/log4net/Repository/LoggerRepositorySkeleton.cs
- src/site/xdoc/release/release-notes.xml
> fix IndexOutOfRangeException when creating child loggers multithreaded

- examples/Appenders/SampleAppendersApp/Appender/AsyncAppender.cs
- examples/Appenders/SampleAppendersApp/Appender/FireEventAppender.cs
- examples/Appenders/SampleAppendersApp/Appender/MessageBoxAppender.cs
- examples/Appenders/SampleAppendersApp/Appender/MessageObjectExpanderAppender.cs
- examples/Appenders/SampleAppendersApp/Appender/PatternFileAppender.cs
- examples/Appenders/SampleAppendersApp/Appender/PatternLayoutAdoNetAppender.cs
- examples/Appenders/SampleAppendersApp/Appender/PatternLayoutAdoNetAppenderParameter.cs
- examples/Appenders/SampleAppendersApp/LoggingExample.cs
- examples/Appenders/WmiAppender/IWmiBoundEvent.cs
- examples/Appenders/WmiAppender/WmiAppender.cs
- examples/Appenders/WmiAppender/WmiAppender.csproj
- examples/Appenders/WmiAppender/WmiInstaller.cs
- examples/Appenders/WmiAppender/WmiLayout.cs
- examples/Appenders/WmiAppender/WmiLoggingEvent.cs
- examples/Directory.Build.props
- examples/Extensibility/EventIDLogApp/EventIDLogApp.cs
- examples/Extensibility/TraceLogApp/TraceLogApp.cs
- examples/Extensions/log4net.Ext.EventID/EventIDLogImpl.cs
- examples/Extensions/log4net.Ext.EventID/EventIDLogManager.cs
- examples/Extensions/log4net.Ext.EventID/IEventIDLog.cs
- examples/Extensions/log4net.Ext.Trace/ITraceLog.cs
- examples/Extensions/log4net.Ext.Trace/TraceLogImpl.cs
- examples/Extensions/log4net.Ext.Trace/TraceLogManager.cs
- examples/Layouts/SampleLayoutsApp/Layout/ForwardingLayout.cs
- examples/Layouts/SampleLayoutsApp/Layout/LevelConversionPattern.cs
- examples/Layouts/SampleLayoutsApp/Layout/LevelPatternLayout.cs
- examples/Layouts/SampleLayoutsApp/Layout/LineWrappingLayout.cs
- examples/Layouts/SampleLayoutsApp/LoggingExample.cs
- examples/Performance/NotLogging/NotLogging.cs
- examples/Tutorials/ConsoleApp/LoggingExample.cs
file scoped namespaces and CA warnings fixed in examples
> file scoped namespaces and CA warnings fixed in examples

- src/log4net.Tests/Core/LoggingEventTest.cs
- src/log4net/Core/LoggingEvent.cs
While working on getting log4net.Ext.Json package to work with log4net 3 I noticed a regression. With log4net 2.0.10  the test checking if the user name is as expected worked both during local run on my Windows machine and on the CI Linux agent used by Gitlab. After upgrading log4net to version 3.0.1 it stopped working on the CI and started reporting that the user name is an empty string.
Passing:
https://gitlab.com/gdziadkiewicz/log4net.Ext.Json/-/jobs/7522362244
Failing:
https://gitlab.com/gdziadkiewicz/log4net.Ext.Json/-/jobs/8094529032#L172
It would be great to be able to run tests for log4net on all combinations of frameworks and OSes automatically (would you be interested in someone getting started work on it?).
In the meantime it draws as important for me to test (not sure about …
> Fix empty string received by .NET 8 users on Linux on userName

- src/log4net.Tests/Appender/AdoNetAppenderTest.cs
- src/log4net.Tests/Appender/AppenderCollectionTest.cs
- src/log4net.Tests/Appender/FileAppenderTest.cs
- src/log4net.Tests/Appender/RollingFileAppenderTest.cs
- src/log4net.Tests/Appender/TelnetAppenderTest.cs
- src/log4net.Tests/Appender/TraceAppenderTest.cs
- src/log4net.Tests/Context/LogicalThreadContextTest.cs
- src/log4net.Tests/Core/FixingTest.cs
- src/log4net.Tests/Core/LevelMappingTest.cs
- src/log4net.Tests/Core/LevelTest.cs
- src/log4net.Tests/Core/LoggingEventTest.cs
- src/log4net.Tests/Filter/FilterTest.cs
- src/log4net.Tests/Hierarchy/HierarchyTest.cs
- src/log4net.Tests/Layout/DynamicPatternLayoutTest.cs
- src/log4net.Tests/LoggerRepository/ConfigurationMessages.cs
- src/log4net.Tests/Signing.cs
- src/log4net.Tests/Util/LogLogTest.cs
- src/log4net.Tests/Util/PatternConverterTest.cs
- src/log4net.Tests/Util/PatternStringTest.cs
- src/log4net.Tests/Util/SystemInfoTest.cs
- src/log4net.Tests/Util/TransformTest.cs
- src/log4net.Tests/log4net.Tests.csproj
- use raw strings for config files in unit tests
- fixed more warnings
> use raw strings for config files in unit tests

- .github/workflows/build.yaml
Our Ubuntu build fails on the new ubuntu-24.04 image. This change forces use of the old image to keep us green while we adjust to the new image.
> Keep old, working ubuntu image version.

- src/log4net/Appender/FileAppender.cs
- src/log4net/Appender/RollingFileAppender.cs
A change to `FileAppender` that breaks backward compatibility was introduced with #196.
Renamed `SetQwForFiles` back to `SetQWForFiles` in order to restore compatibility with types that extend `FileAppender`
Fixes #216
> fixed SetQWForFiles method name in FileAppender from #196

- .github/FUNDING.yml
This adds sponsors buttons to this repository as [documented by GitHub](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository).
The list is based on the [list of committers accepting GitHub Sponsorship](https://logging.apache.org/support.html#sponsorship-github) intersected with the [official list of active `Log4net` members](https://logging.apache.org/team-list.html). It is related to apache/logging-log4j2#3580
> Add "Sponsor" buttons to repository

- src/log4net.Tests/Appender/RollingFileAppenderTest.cs
- src/log4net.Tests/Appender/RollingFileAppenderWithDirTest.cs
- src/log4net/Appender/RollingFileAppender.cs
Fix #231 
`PreserveLogFileNameExtension` was cutting off the directory part that could be present on config's `File` option. It resulted in unbound rolling of files in the scenario described in the linked issue.
Fix the issue by making the `PreserveLogFileNameExtension` code branch handle the directory correctly.
It can be tested with the configuration provided in linked issue.
> Handle logs with positive CountDirection, extension preservation and placed in dir

- src/changelog/3.1.1/.release-notes.adoc.ftl
- src/changelog/3.1.1/.release.xml
- src/changelog/3.1.1/245-ndc-inherit.xml
- src/log4net.Tests/NdcTest.cs
- src/log4net.sln
- src/log4net/Util/ThreadContextStack.cs
> #246 fix InvalidCastException in ThreadContextStack.InternalStack.set

- src/log4net.Tests/Layout/PatternLayoutTest.cs
- src/log4net/DateFormatter/AbsoluteTimeDateFormatter.cs
fix #247 by storing the timestamp together with the cached time-string
> Fix caching of time strings in AbsoluteTimeDateFormatter

- src/log4net/Core/LoggerManager.cs
When log4net is used in an AssemblyLoadContext that should be unloaded, log4net blocks the unloading since it subscribed to event handlers from the default load context. This PR aims to cleanup the 2 subscriptions that most likely cause this behaviour.
Related discussion here: https://github.com/dotnet/runtime/issues/116142 also contains a working demo of the problem.
Note that I did not fully test the solution yet. But this cleanup is a good measure in any case.
> Shutdown: Unsubscribe from AppDomain event handlers

- src/changelog/3.2.0/.release.xml
- src/changelog/3.2.0/250-broken-rolling-logfiles.xml
- src/log4net.Tests/Appender/RemoteSyslogAppenderTest.cs
- src/log4net.Tests/Integration/Log4NetIntegrationTests.cs
- src/log4net.Tests/Integration/MockDateTime.cs
- src/log4net.Tests/Integration/log4net.no_file_name.config
- src/log4net.Tests/Integration/log4net.roll.config
- src/log4net/Appender/RollingFileAppender.cs
- src/log4net/Util/Log4NetAssert.cs
- added release notes
- added license headers
- adjusted Log4NetIntegrationTests to .editorconfig
> #250 mocked DateTimeStrategy to speedup test

- src/changelog/3.2.1/268-shorten-test-output.xml
- src/log4net.Tests/Util/LogLogTest.cs
- src/log4net/Util/LogLog.cs
The console output in the log4net unit tests was much too long (caused by a single test).
> shorten console output for unit tests
